
[model]

z_dim = 800
log_sysnoise = -4
log_obsnoise_model = 0
block_step = 1
aux_alpha = 0
lr = 3e-3
time_sequence_length = 1
G_val = 1e-5
batch_size = 64
take_physical_loss = True
load_model = False
load_model_path = ""
jump_step_loss_setting = pattern1
variable_kernelsize = False
kernel = 5
lr_10percent_iters = 25000

[data]
dt = 0.03
N_data = 25600512
data = complete
obsnoise = 1.0
train_data_seed = 10
test_data_seed = 1100000
n_step = 80
m_step = 20
n_step_test = 80
m_step_test = 20

[others]
outdir = Lorenz96_physspace_complete/DDP_obsnoise1_dt003/cond1
